% 每一個track 代表一個影片中的移動物體。
%
% id:                       辨識物體之編號
% bbox:                     辨識物體的bounding box
% kalmanFilter:             kalman濾波器物件用以執行物體追蹤
% age:                      自從該物體出現後持續了多少個frame，即存活了多久
% totalVisibleCount:        該物體於出現後可見到的frame個數(注意age>=totalVisibleCount)
% consecutiveInvisibleCount:the number of consecutive frames for
%                           which the track was not detected (invisible)



function tracks = initializeTracks()
tracks = struct(...
            'id', {}, ...
            'bbox', {}, ...
            'kalmanFilter', {}, ...
            'age', {}, ...
            'totalVisibleCount', {}, ...
            'consecutiveInvisibleCount', {}, ...
            'speed', {});